version: 2

project_name: slackcli

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: slackcli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/cgrossde/slackcli/cmd.version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: cgrossde
    name: slackcli
  draft: false
  make_latest: true

homebrew_casks:
  - name: slackcli
    binaries:
      - slackcli
    repository:
      owner: cgrossde
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/cgrossde/slackcli"
    description: "Slack CLI optimized for usage by LLMs or in scripts"
    license: "MIT"
    generate_completions_from_executable:
      executable: "bin/slackcli"
      args:
        - completion
      shell_parameter_format: cobra
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slackcli"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
